/**
 *  L - Attempt or loading for progress dialog
 *  S - success
 *  F- failed
 */

const type = {
  /*Login*/
  LOGIN_L: 'LOGIN_L',
  LOGIN_S: 'LOGIN_S',
  LOGIN_F: 'LOGIN_F',

  /*Register*/
  REGISTER_L: 'REGISTER_L',
  REGISTER_S: 'REGISTER_S',
  REGISTER_F: 'REGISTER_F',

  LOG_OUT :'LOG_OUT',
  GUEST_LOGIN :'GUEST_LOGIN',
  ADD_ADDRESS_S: 'GET_ADDRESS_S',
  GET_ADDRESS_S: 'GET_ADDRESS_S',
  VEW_ORDER_S: 'VEW_ORDER_S',
  GET_FAVORITE_DISH: 'GET_FAVORITE_DISH',
  PLACE_ORDER: 'PLACE_ORDER',
  UN_FAVORITE_DISH: 'UN_FAVORITE_DISH',
  DELETE_ADDRESS: 'DELETE_ADDRESS',
  SELECTED_LAT_LNG: 'SELECTED_LAT_LNG',
  SELECT_ADDRESS: 'SELECT_ADDRESS',
  GET_HOME_MEALS: 'GET_HOME_MEALS',
  GET_MEAL_DETAIL :'GET_MEAL_DETAIL',
  GET_CATEGORY_MEALLIST: 'GET_CATEGORY_MEALLIST',
  GET_MEAL_CATEGORY: 'GET_MEAL_CATEGORY',
  GET_RESTAURANT_LIST: 'GET_RESTAURANT_LIST',
};

export { type };
